[project]
name = "basic-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.10.1",
    "pandas>=2.3.0",
    "pyarrow>=20.0.0",
]
